### ISSUE TITLE
error when executing "canvas: Running install script"

### ISSUE THREAD

**Issue by Alexandro521** [Gusarovv/discord-card-canvas#98]
**I tried to install the package with pnpm and I got this error**

![image](https://github.com/user-attachments/assets/392da0df-e2e9-4a00-9a00-82503ffe53aa)

### node version
  **22.11.0**

### OS version
  **Windows 10 Pro Education 22H2**

**Comment by Gusarovv** [comment]
I checked it on a similar system. I didn't find any problems when calling the command (pnpm add discord-card-canvas).
Have you tried cleaning and verifying the npm cache?

You can try to completely remove the library from the project first and install it again

**Comment by Alexandro521** [comment]
I managed to find the root of my problem, I will not give a technical explanation for the moment but basically there was a conflict between my version of Node JS 22.11 and my installed versions of Visual Studios that only have support up to Node 21.

Using a version lower than Node 21 the installation is done correctly, for later versions of Node you must install the most recent version of Visual Studio with "Desktop development with C++"

node js 20

![image](https://github.com/user-attachments/assets/6796361a-09ba-4f28-bf91-ee5730f0ce6f)

node js 22

![image](https://github.com/user-attachments/assets/c4fef7c3-65ea-4916-af67-b77a933f06f6)

installation with pnpm and node js 20 

![image](https://github.com/user-attachments/assets/4e6fa35e-b994-444f-959b-0a316a3e5e99)
